version: '3.8'
services:
  api1:
    image: rinha:latest
    expose:
      - "8080"
    environment:
      MONGO_HOST: mongo-api
      # MONGO_USER: admin
      # MONGO_SECRET: secret
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.475'
          memory: '100MB'

  api2:
    image: rinha:latest
    expose:
      - "8080"
    environment:
      MONGO_HOST: mongo-api
      # MONGO_USER: admin
      # MONGO_SECRET: secret
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.475'
          memory: '100MB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - mongo
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '25MB'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - vol-mongo:/data/db
    restart: always
    container_name: mongo-api
    # environment:
    #     MONGO_INITDB_ROOT_USERNAME: admin
    #     MONGO_INITDB_ROOT_PASSWORD: secret
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '305MB'


volumes:
  vol-mongo: